name: clean_network
description: A new Flutter package project.
version: 0.0.1
homepage: "https://github.com/"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.15.0
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  


flutter:

